### ISSUE TITLE
TypeError: weaponsArray[weaponName] is undefined

### ISSUE THREAD

**Issue by hongshaoyang** [tsitu/MH-Tools#116]
On the Best Setup Tool page, clicking Calculate causes a TypeError: `weaponsArray[weaponName] is undefined`. See the following code:

https://github.com/tsitu/MH-Tools/blob/761cda979adb4009610c05a444fe09505d82aa23/src/main/shared-cre-setup.js#L249-L252

**Comment by tsitu** [comment]
Thanks for the report. Unfortunately, I'm unable to reproduce this on my end.

- Have you tried refreshing via Ctrl + F5?
- Have you imported your items in via the latest 'Best Setup: Load Items' bookmarklet?
- Is there a particular item you suspect is triggering this error?
