### ISSUE TITLE
User location in bm.menu.js

### ISSUE THREAD

**Issue by Hazado** [tsitu/MH-Tools#119]
location variable needs updating for recent Mousehunt update

https://github.com/tsitu/MH-Tools/blob/6992f9974cb4f31ddb649e9112468c4635f8fb55/src/bookmarklet/bm-menu.js#L224

**Comment by tsitu** [comment]
Thanks! Fixed in eaa77158674d208b059745ead864b02337a7d0c8, and moved the click handler to location image icon in 4afb6c6e64690a6133ee26c244c0b9303eee9c0a based on Discord feedback.
