### ISSUE TITLE
Fort Rox

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#12]
Population data collection
https://www.mousehuntgame.com/forum/showthread.php?128603-Fort-Rox-Population-Data

Mouse powers
https://docs.google.com/spreadsheets/d/1cGu0eG0Fgwf-OWFAfed_tVJC0GQh-j6utxiSDdWRFZE/edit#gid=1981316495

**Comment by Babalela01** [comment]
Upgrade effects for at least ballista and cannon should be included and we can maybe consider adding wall damage per mouse.

**Comment by tsitu** [comment]
Current population data and mouse powers for Fort Rox added in ca6cf92c49479570541cc041a6d3c4e5426c57e5 and 2cd8fcaf80a2f2979cf36b3d579856198a5d3fcf. Still need to integrate with CRE bookmarklet and implement ballista/cannon effects.
