### ISSUE TITLE
Is this a known value or an estimate? 

### ISSUE THREAD

**Issue by eraymitrani** [tsitu/MH-Tools#126]
https://github.com/tsitu/MH-Tools/blob/2975964ce766c5d323e435abdc506be196f8e7e3/src/main/shared-cre-setup.js#L1412

**Comment by tsitu** [comment]
See https://github.com/tsitu/MH-Tools/commit/1365d6d0a4a87a9f313dd458bf8f60a68876967d and https://github.com/tsitu/MH-Tools/issues/12 for context around its implementation. Since these don't answer the question directly I'm inclined to believe it was a guesstimate.
