### ISSUE TITLE
Update Catch Rate Formula 

### ISSUE THREAD

**Issue by AardWolf** [tsitu/MH-Tools#127]
We've got a new estimate of the catch rate formula (https://discordapp.com/channels/275500976662773761/355474934601875457/705884023943200888) which leads to a new minluck formula:

`ceil(ceil(sqrt(mp/4))/min(1.4,effectiveness))`

**Comment by tsitu** [comment]
See https://github.com/tsitu/MH-Tools/pull/128#issuecomment-691321166
