### ISSUE TITLE
Zokor districts in CRE bookmarklet

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#13]
The CRE bookmarklet doesn't read the district names in Zokor.

It can be found in the user variable: 
quests.QuestAncientCity.district_name

**Comment by tsitu** [comment]
These need to be manually noted because they differ slightly from expected (e.g. "The" in front of some districts, "Tech" in front of Manaforge, etc)

**Comment by Babalela01** [comment]
Okay, I''m noting those names as I get to the districts. On further inspection there are also 'district_tier' and 'clue_name' properties which might work easier then. 

Extra names so far:
The Master Scholar Auditorium
The Templar's Fealty Sanctum

**Comment by tsitu** [comment]
Nice workaround! Won't be able to test this much in the near future but I'm confident it works.

**Comment by Babalela01** [comment]
No further comments/complaints so I'm closing this now.
