### ISSUE TITLE
RFE: option to exclude denture bases from best setup

### ISSUE THREAD

**Issue by josephks** [tsitu/MH-Tools#138]
The top options of the best setup page are dominated by the charged denture bases, but I rarely want to use toothlets when hunting.  Please have an option to exclude.  There used to be a way to manually edit my trap inventory but not anymore.

**Comment by tsitu** [comment]
This has been on my TODO list for some time now. Thank you for the reminder. Implemented in 74784d5d42939460a6db256c73a3a5dacc0fad58

> There used to be a way to manually edit my trap inventory but not anymore.

Could you briefly elaborate on this?

**Comment by josephks** [comment]
There used to be a page with a long list of checkboxes where you could edit your inventory.  If that page still exists I can't find it.  The only way to update your inventory that I can find is to click on the "Bast Setup: Load Items" button in the autoloader or the bookmarklet.

**Comment by josephks** [comment]
Thank you for the quick fix.

**Comment by tsitu** [comment]
> There used to be a page with a long list of checkboxes where you could edit your inventory. If that page still exists I can't find it. The only way to update your inventory that I can find is to click on the "Bast Setup: Load Items" button in the autoloader or the bookmarklet.

That functionality hasn't changed and still exists via the buttons shown in the image below:

![bsetup](https://user-images.githubusercontent.com/6689581/99736925-1580b580-2a7c-11eb-88cd-7882295acecb.PNG)

Feel free to ping me here if you have any issues with the new feature!
