### ISSUE TITLE
Glowing Gourd Charms in Labyrinth/Zokor

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#14]
Effect of Glowing Gourd Charms on population in Labyrinth/Zokor
http://mhwiki.hitgrab.com/wiki/index.php/Glowing_Gourd

**Comment by tsitu** [comment]
115 recorded hunts in Labyrinth/Zokor as of [this](https://github.com/DevJackSmith/mh-hunt-helper/commit/7e1ec68b12ca8c2d4a2fe4c3bb2596ac18d35704) nightly backup.

```sql
where charm_id = 1940 and (location_id = 51 or location_id = 52)
```

**Comment by tsitu** [comment]
Moved to #79
