### ISSUE TITLE
Aura dropdowns as opposed to manual custom values

### ISSUE THREAD

**Issue by tsitu** [tsitu/MH-Tools#15]
http://mhwiki.hitgrab.com/wiki/index.php/Aura

**Comment by Babalela01** [comment]
Just remember that a player can have multiple active auras at the same time so a simple dropdown list will not be sufficient. The html multi-select is akward to use so checkboxes or a custom jquery widget is probably better.

**Comment by tsitu** [comment]
@Babalela01 
Closing this one because it would add unnecessary complexity - I remember there being one event semi-recently where you could earn an increasing luck bonus. We'll just have to keep improving the automatic CRE bookmarklet parsing I guess!

**Comment by tsitu** [comment]
Re-opening because of increased demand after the introduction of consistently obtainable auras like Chrome and Lightning. Checkboxes seem like the best implementation solution as of now.

**Comment by tsitu** [comment]
Added Chrome, Slayer, and Lightning aura checkboxes in b16ab6eeb486db04c7a24a97743f06acc31a6873. 

TODO: Implement automatic parsing for bookmarklets

**Comment by tsitu** [comment]
Removed checkboxes in favor of a 'Bonus Power %' field in f1457f0660a27796b82b5ced5021602b44b350d0 (implicitly supports all current/future auras and is easy to parse/calculate via `user.trap_power_bonus`)
