### ISSUE TITLE
Cheese attraction rates

### ISSUE THREAD

**Issue by tsitu** [tsitu/MH-Tools#18]
Verify accuracy of baselineAttArray values in arrays.js via HornTracker analysis or other means.  [This](http://mousehuntguideforyou.weebly.com/cheddar-cheese.html) site claims Cheddar has 58.5% AR while we use 50%.

**Comment by Babalela01** [comment]
We also need to check he BWRift cheese baseline attractions. Bo ASC and RSC are se to 99% which might not be correct

**Comment by tsitu** [comment]
Finally wrote a decent script to calculate a cheese's empirical AR using Jack's DB. Going to write down my implementation here for reference:

1. Run the following SQL query to get an array of objects into JS, replacing `cheese_id` as desired (`attraction_bonus` can be increased up to 100 given sufficient sample sizes): 
```sql
SELECT attraction_bonus, attracted FROM `jacksDB`.hunts
WHERE cheese_id = 120 
AND attraction_bonus < 90
```
2. Map through this array, caching unique `attraction_bonus` values.
3. Iterate through the cache and filter original array over each element. If the filtered array length is greater than 50 (arbitrary global minimum sample size), filter it again over `attracted = 1`. The length of the resultant array divided by the previous one is the `Measured AR`.
4. Calculate 'actual' AR using `(Measured AR - Bonus) / (1 - Bonus)`, and push it onto a global array, along with its corresponding sample size.
5. Reduce over this global array to get total sample size.
6. Reduce again to get a weighted average 'overall' AR.

Output for Ancient String Cheese (id 2343):
`
Total sample size: 9451 / 
Average sample size: 1050.11 / 
Overall Calculated Cheese AR: 98.70%
`

Output for Runic String Cheese (id 2344):
`
Total sample size: 50917 / 
Average sample size: 3636.93 / 
Overall Calculated Cheese AR: 99.97%
`

Output for Gouda (id 98):
`
Total sample size: 130498 / 
Average sample size: 3107.10 / 
Overall Calculated Cheese AR: 84.79%
`
