### ISSUE TITLE
Iceberg Boiler base needs to be ultimate

### ISSUE THREAD

**Issue by DevJackSmith** [tsitu/MH-Tools#200]
reported in discord:
when I use the latest auto-loader bookmarklet from the CRE, it doesn't detect my iceberg boiler as an ultimate iceberg base
it sets the area as "The Mad Depths" when it should be "The Mad Depths (Ultimate Iceberg)"

**Comment by plasmoidia** [comment]
The change would need to be made here:
https://github.com/tsitu/MH-Tools/blob/b406513d3f77faf94542082ecdd070b96ccd7937/src/bookmarklet/bm-cre.js#L146

I think it just needs an or condition to check if the base is the Iceberg Boiler Base.

**Comment by plasmoidia** [comment]
IBB also needs UIB/Deep Freeze bonus stats here:
https://github.com/tsitu/MH-Tools/blob/b406513d3f77faf94542082ecdd070b96ccd7937/src/main/shared-cre-setup.js#L383
