### ISSUE TITLE
jsdelivr not up to date 

### ISSUE THREAD

**Issue by hymccord** [tsitu/MH-Tools#258]
As a side-effect of migrating to GitHub Actions and deploying via `action/deploy-pages` (which uses the [github deployment API](https://docs.github.com/en/rest/deployments?apiVersion=2022-11-28)), the `gh-pages` branch is no longer updated since that was what TravisCI used to deploy. The latest SHA it pulls is from a over 4 months ago meaning the autoloader doesn't get up-to-date bookmarklets.

Is there any risk to using `https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-<tool>.min.js` for the bookmarklets? This is the URL that mhct-extension uses to grab bookmarkets on publishing.  

The json data would need to pulled from the `tsitu.github.io/mh-tools/data/json/` since jsdelivr doesn't support those URLs.

**Comment by tsitu** [comment]
> Is there any risk to using https://cdn.jsdelivr.net/gh/tsitu/MH-Tools@master/src/bookmarklet/bm-<tool>.min.js for the bookmarklets?

That should be fine, I wasn't aware that jsDelivr auto-minifies when you add `.min`. We could probably remove the `minify:bookmarklet` step from the build process once this is implemented 👍
