### ISSUE TITLE
Battering Ram Mouse

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#26]
Attraction & Mouse Power

**Comment by tsitu** [comment]
115 recorded attractions using SB+ or Gouda in Jack's DB as of [this](https://github.com/DevJackSmith/mh-hunt-helper/commit/7e1ec68b12ca8c2d4a2fe4c3bb2596ac18d35704) nightly backup.

```sql
mouse_id = 669 and (cheese_id = 114 or cheese_id = 98)
```

**Comment by tsitu** [comment]
Moved to #79
