### ISSUE TITLE
Naughty List Printing Press Base Bonus should only apply in Folklore Forest

### ISSUE THREAD

**Issue by Mistborn94** [tsitu/MH-Tools#293]
**Affected Tools:** CRE & Best Setup

The boosted stats for Naughty List Printing Press Base should only apply in Folklore forest, right now it applies in all locations. 

When using a 0-luck trap with the Naughty List Printing Press Base, I expect the total luck to be 10, but instead it is 57
![image](https://github.com/tsitu/MH-Tools/assets/9079017/4c33b64e-b3a4-42ab-8ad8-1cc55e16d8bb)

The paperless version has the correct, unboosted stats: 
![image](https://github.com/tsitu/MH-Tools/assets/9079017/b55bfb02-024f-487f-b711-b3ef5e7d8449)

**Comment by SuperMari0s** [comment]
I was thinking (to implement) we should have a checkbox to filter the Printing Press Base like we do with denture.

**Comment by hymccord** [comment]
It's not quite as simple as SSDB b/c SSDB works everywhere whereas the NLPP only works in a certain area.

I've got it on my radar to tackle it.

**Comment by tsitu** [comment]
This should be addressed by https://github.com/tsitu/MH-Tools/commit/cafb8b8f2bc49b9bb5000326cb34d2d3bdf1caf7

Let me know if there any issues!
