### ISSUE TITLE
Improve Saving/Loading of owned items 

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#30]
https://www.mousehuntgame.com/forum/showthread.php?95543-Catch-Rate-Calculator&p=1369336&viewfull=1#post1369336

> I would prefer it if the selection of weapons, bases and charms didn't get reset to ALL every time something new gets added, maybe you could just leave it as is and we can add the check mark for the new item if we choose to? 

Implementing this will require changing how the saving works. Using a list of names instead of basing it on array indexes could work, but we need to investigate storage limitations before implementing it.

**Comment by tsitu** [comment]
Implemented using localStorage in 8aacfd8006e5d3234dbe42d150ebd4e2e701c7d4
