### ISSUE TITLE
Rift Stalker Codex

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#32]
Hunters with the codex will have a 20% Power Bonus and +10 Luck added to their trap when three pieces of Rift equipment are armed.

**Comment by tsitu** [comment]
I haven't been able to find a reference to owning either the Null Gauntlet or Riftstalker Codex in the JS user object. Do we have to infer this?

**Comment by Babalela01** [comment]
Inferring it from the total luck/power might be error prone due to the large amount of possible bonusses (auras, events etc). I have not found a solution for bookmarklet integration yet, but have considered saving it in a cookie once a user has selected it - its not someting they are likely to loose.
