### ISSUE TITLE
Nightlight charm effect

### ISSUE THREAD

**Issue by groupsky** [tsitu/MH-Tools#39]
Implement the power boost of nightlight charm. First find a table (stage -> power bonus)

**Comment by groupsky** [comment]
Stage | Power
---------|---------
Day | 120
Twilight | 120
Midnight |
Pitch |
Utter Darkness |
First Light |
Dawn | 821

**Comment by wbxlll** [comment]
![image](https://user-images.githubusercontent.com/17880187/45018740-4328e200-b05d-11e8-9c18-efe3f280053d.png)

**Comment by tsitu** [comment]
Implemented in e06af3f0f2093af816a1e2fbf8e6e8dafdaf00f8. Thanks @wbxlll!
