### ISSUE TITLE
Bookmarklet Bonus Luck incorrect

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#40]
Bonus luck calculated from total luck url paramter is incorrect when invalid cheese is selected

https://tsitu.github.io/MH-Tools/cre.html?location=Forbidden%20Grove&weapon=Chrome%20Grand%20Arcanum%20Trap&base=Fissure%20Base&charm=Ancient%20Charm&totalluck=47&cheese=Gouda&rank=grandduke&

**Comment by tsitu** [comment]
@Babalela01 
Fixed, once again with the side effect of prioritizing cheese and charms specified in URL (which unintentionally addresses [this complaint](https://www.mousehuntgame.com/forum/showthread.php?95543-Catch-Rate-Calculator&p=1373881&viewfull=1#post1373881))

**Comment by tsitu** [comment]
Re-opening because I just realized that this bug occurs whenever _any_ URL parameter is invalid.
