### ISSUE TITLE
Living Garden SB population

### ISSUE THREAD

**Issue by groupsky** [tsitu/MH-Tools#41]
It seems in living garden the population changes when using sb. Especially Strawberry Hotcakes attraction raises to 23.7%

http://www.horntracker.com/index.php?location=301|false&cheese=3|false

**Comment by groupsky** [comment]
I just built a [tool](https://www.npmjs.com/package/horntracker-client) to extract population (and other stuff) from HT. Could come in handy for updating the population. In this particular case one should run
`ht-cli pop --vars.location.living\ garden --vars.cheese.sb -o csv -a 1`
 and then add the result to populations data.

**Comment by tsitu** [comment]
Very nice tool. I'll be playing around with it to see if I can accurately and efficiently update problematic populations like these.

**Comment by tsitu** [comment]
One important option that I can't find in your tool is phases a.k.a. sublocations. In this particular case, Strawberry Hotcakes may very well be the most attracted mouse using SB+. However, the proportions for 'Poured' vs. 'Not Poured' are different once Thirsty is added into the former's mouse pool.

**Comment by groupsky** [comment]
`ht-cli pop --vars.location.living\ garden --vars.bucket\ state.1 --vars.cheese.sb` should give for not poured, and `--vars.bucket\ state.2` for poured. 

All the filters available in the web ui, should be available with the same name. I'll see if I can make it more user friendly, like `--vars.poured` and `--vars.not-poured`

**Comment by tsitu** [comment]
Moved to #79
