### ISSUE TITLE
Bristle Woods Rift & Moussu Picchu Bookmarklets

### ISSUE THREAD

**Issue by Babalela01** [tsitu/MH-Tools#51]
CRE bookmarklets needs to be updated to include BWR phases.
Map bookmarklet might need work depending on mice names.

**Comment by tsitu** [comment]
Tacking Moussu Picchu onto this as well. Both should be fairly straightforward.

**Comment by Babalela01** [comment]
BWR completed in a1e7f38334e1a28876d59beddc95746455b8be48

**Comment by groupsky** [comment]
Haven't started with MoPi yet, so don't have strong need for the cre update. If someone has time can do it.

Note - the map bookmarklet (or the map tool) should truncate `Ful'Mina`'s full name to just the first part.

**Comment by Babalela01** [comment]
I'm not 100% happy with truncating names as that complicates bookmarklet & app logic and population updates, all names should rather be escaped in the URL. But whoever gets around to implementing this can decide.
