### ISSUE TITLE
Incorrect total catch rate

### ISSUE THREAD

**Issue by groupsky** [tsitu/MH-Tools#56]
Seems the calculation for total catch rate doesn't always reflect the individual columns:

![catch-rate-total](https://user-images.githubusercontent.com/185580/32648112-09ee5ccc-c5fd-11e7-8eb0-fb93d22999ab.png)

This happens on MoPi when using GGC or SB, on Brie/Gouda the total value is 100%. I'm guessing a problem with population data, but haven't investigated.

**Comment by tsitu** [comment]
That's the average catch rate: `averageCR = overallCR / overallAR * 100`

I'm going to rework the bottom row to indicate more clearly whether each column is supposed to be a sum, average, or something else :grin:

**Comment by groupsky** [comment]
Actually if you notice the bottom column:

1. the AR total does not equal the sum of displayed individual AR
2. the CR average should be `100%` when all individial CR's are `100%`
3. the Catches/100 hunts seems to be the only correct total/average number.

**Comment by tsitu** [comment]
You're right, GGC and SB+ attraction rates add up to 99.94% (instead of 100%) in the data.

**Comment by tsitu** [comment]
This has been addressed in e397e28297673622577c97714ef129fbc9681a64, but there are still some lingering populations which are +/- 0.01% to 0.03% off from 100% due to hundredths-place rounding errors.

**Comment by groupsky** [comment]
If we do a normalization at some point, that should fix it - probably best in the cre tool, to minimize rounding errors.
