### ISSUE TITLE
Population affected by wind/rain levels

### ISSUE THREAD

**Issue by groupsky** [tsitu/MH-Tools#60]
The potion farming population is affected by wind/rain levels so I suggest to include these affects. This also means that instead of the current sublocation divisions, it would be better if we have sublocations similar to WWRift: `Low/Low`, `Medium/Medium`, ...

Ref #51

**Comment by Babalela01** [comment]
To make this work correctly for Rainy/Windy cheese too, I see two options:
- Add population data for these for Rainy/Windy each of the new phases. This will cause duplication.
- Get smarter about handling populations with multiple phases. (But maybe only when we get around to actually redesigning this whole thing?). This is a lot of additional complexity.

**Comment by groupsky** [comment]
> * Add population data for these for Rainy/Windy each of the new phases. This will cause duplication.

If I'm not missing something else the duplication will be on the rainy/windy/dragony - but other than making the file slightly bigger (there are only 2-3 mice in population per cheese) I don't see any other issue.

> * Get smarter about handling populations with multiple phases. (But maybe only when we get around to actually redesigning this whole thing?). This is a lot of additional complexity.

Actually I think we should make it less smart about specific locations and conditions - just a simple set of generic rules.

**Comment by tsitu** [comment]
How significant are the differences in potion drop rates for say Medium/Medium versus base level? Would it be viable to build up both sides to farm, or is this data just for when you run out of Dragonvine at Max/Max and use Gouda/GGC all the way down?

**Comment by groupsky** [comment]
For instance Cloud Collector and Windy Farmer goes from 15% up to around 50% depending on the wind/rain levels. And these are the mice that drop potions every time.

**Comment by tsitu** [comment]
Moved to #79
