### ISSUE TITLE
Map tool: Provide possibility for selecting available cheeses

### ISSUE THREAD

**Issue by bavovanachte** [tsitu/MH-Tools#71]
Hi,

First of all, thanks for this wonderful tool. It's a real timesaver :+1: 

I was wondering if it makes sense to add the possibility to select which cheeses are available to you when solving a map.
What triggered this issue for me is that on a not-so-important map, I might not want to use any SB+ when trying to finish it. 
Could be similar to how you can disable specific charms/bases/weapons in the "Best trap setup"?

I'm willing to make this contribution myself (trying to find opportunities for learning javascript, am an embedded SW developer), but want to check first to see if this is something that makes sense.

**Comment by tsitu** [comment]
Hi Bavo, that's a great idea which has been brought up before on the forums. I'd also be willing to implement this once a consensus is reached on how it should look.

Checkboxes would work, but seem unwieldy and liable to clutter the UI. I was thinking about adding functionality to the text input (auto-complete included) to filter out specific cheeses. Prefixing a cheese name with the minus (-) sign disables it (e.g. "-SUPER|brie+" or "-Magical String Cheese"). How does that sound?

**Comment by bavovanachte** [comment]
Hi,

- In that case, would it need to be added for every mouse in the list? Or would you consider a separate line in the text box just for the cheese selection?
- I think it would be useful to be able to disable in one go all the SB+/magic essence based cheeses (SB+, maki, magical string cheese,...). Could we group those in a specific keyword?

**Comment by bavovanachte** [comment]
Maybe "-Event" for event cheese?

Just writing up a couple of scenario's to make sure we're aligned:

- Only use cheese found in the Cheese Shoppe:
```+Cheese Shoppe```. I guess this would imply something like ```-All +Cheese Shoppe```?
- Do not use any cheese crafted using magic essence:
```-Magic Essence```
- Do not use any cheese crafted using magic essence, except for Maki:
```-Magic Essence +Maki```
- Only use cheese found in the Cheese Shoppe, except for Gouda:
```+Cheese Shoppe -Gouda```

Does this make sense? Or am I overthinking this?

**Comment by tsitu** [comment]
Apologies for the delayed response. Your scenarios make sense - I had not actually considered the possibility of using (+) in combination with (-). In that case, it may be best to add a separate, smaller textarea (beneath the mouse one) solely for cheese filtering.

The next step is to group certain cheeses into categories like "Cheese Shoppe" or "Crafted". Once that's done I can stick them into arrays and start implementing the feature.

**Comment by bavovanachte** [comment]
[MH cheeses categories.txt](https://github.com/tsitu/MH-Tools/files/1671012/MH.cheeses.categories.txt)

A quick categorization based on the information here: http://mhwiki.hitgrab.com/wiki/index.php/Cheese

- Doesn't include the `Magic essence only` category (just based on the info in the "source" column).
- Not sure if all the categories there are useful

So, not exactly finished, but at least a start

**Comment by tsitu** [comment]
It's a solid start. Seems like all of those categories are worth including except `Unstable Curd/Gourd` and `Give to friends`. Throw in `Magic Essence` plus `All` and we're set.

With regards to the Magic Essence category, these are the cheeses I came up with:

- Magical Rancid Radioactive Blue
- Magical String
- Maki
- Maki String
- Moon
- SB+
- Toxic SB+

**Comment by tsitu** [comment]
@bavovanachte

Just pushed up a [feature branch](https://github.com/tsitu/MH-Tools/tree/feature/cleanup-and-cheese-filters) with some initial cheese filter groups. Let me know if the user experience feels intuitive, as I decided to stick with using checkboxes instead of having to manually type in keywords.
